In [1]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [2]:
import random
random.randint(50,100)

65

In [3]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [4]:
scores[:,0]
scores[:,0:1]

array([[77],
       [52],
       [80],
       [97],
       [64],
       [62],
       [89],
       [88],
       [94],
       [58],
       [66],
       [52],
       [60],
       [90],
       [72],
       [83],
       [69],
       [64],
       [72],
       [52],
       [82],
       [95],
       [66],
       [52],
       [89],
       [98],
       [81],
       [68],
       [86],
       [66],
       [58],
       [80],
       [93],
       [65],
       [53],
       [50],
       [94],
       [91],
       [83],
       [61],
       [57],
       [62],
       [51],
       [75],
       [65],
       [58],
       [87],
       [67],
       [57],
       [52]], dtype=int32)

In [5]:
scores[0,:]
scores[0:1,:]

array([[77, 94, 86, 84, 59]], dtype=int32)

In [6]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([80. , 67.2, 70.6, 89.4, 88.2, 67.2, 80.6, 88.8, 84.4, 68.2, 76.8,
       67.8, 72.4, 76. , 73.6, 81.8, 57.4, 73.4, 73.8, 60.6, 73.4, 77.8,
       81.6, 77. , 83.6, 77.8, 79.8, 63.8, 73.2, 76.2, 74.8, 74.6, 82.2,
       76.4, 78.8, 69.6, 74.8, 82. , 75. , 70. , 66.4, 83.6, 73.6, 74.8,
       78.6, 67.8, 78.6, 74. , 69.6, 70.2])

In [7]:
#使用比較運算子
arr = np.random.randn(5)
arr > 0

array([False, False,  True, False,  True])

In [8]:
np.where(arr > 0, 1, 0)

array([0, 0, 1, 0, 1])

In [9]:
np.where(arr > 0, 1, arr)

array([-0.05064401, -1.58382411,  1.        , -1.10662984,  1.        ])