In [20]:
import numpy as np
scores=np.random.randint(50,101,size=(5,5))
scores

array([[ 67,  84,  62,  52,  82],
       [ 75,  93,  65, 100,  98],
       [ 94,  74,  87,  72, 100],
       [ 68,  71,  70,  79,  63],
       [ 69,  57,  62,  81, 100]], dtype=int32)

In [21]:
scores[:3,2:]

array([[ 62,  52,  82],
       [ 65, 100,  98],
       [ 87,  72, 100]], dtype=int32)

In [22]:
scores[4]
scores[4,:3]
scores[4,:]

array([ 69,  57,  62,  81, 100], dtype=int32)

In [23]:
scores[:,:2]

array([[67, 84],
       [75, 93],
       [94, 74],
       [68, 71],
       [69, 57]], dtype=int32)

In [25]:
scores=np.random.randint(50,101,size=(5,5))
scores

array([[ 89,  76,  56,  80,  53],
       [ 69,  95,  98,  85,  85],
       [ 62,  82,  62,  68,  71],
       [ 50, 100,  63,  99,  94],
       [ 82,  59,  97,  78,  97]], dtype=int32)

In [31]:
#加總
np.sum(scores,axis=1)


array([354, 432, 345, 406, 413])

In [ ]:
#平均
np.mean(scores,axis=1)

In [ ]:
#最大
np.max(scores,axis=1)

In [ ]:
#最小
np.min(scores,axis=1)

In [ ]:
#中間數
np.median(scores,axis=1)

In [ ]:
#標準差
np.std(scores,axis=1)