In [9]:
import numpy as np
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.rand(3,4)

array([[0.10148092, 0.84304151, 0.89573188, 0.81185075],
       [0.03770141, 0.7768132 , 0.44217074, 0.97641127],
       [0.77843793, 0.00875666, 0.23045556, 0.23290446]])

In [16]:
np.random.randint(50,101,size=(50,5))

array([[100,  83,  85,  64,  99],
       [ 93,  98,  98,  57,  66],
       [ 56,  98, 100,  98,  81],
       [ 95,  67,  81,  93,  91],
       [ 68,  56,  61,  93,  89],
       [ 89,  80,  51,  67,  71],
       [ 61,  87,  71,  50,  61],
       [ 78,  82,  67,  90,  93],
       [ 55,  90,  65,  87,  68],
       [ 52,  75,  66,  62,  65],
       [ 79,  83,  75,  94,  83],
       [ 73,  91,  64,  62,  59],
       [ 55,  91,  70,  50,  80],
       [100,  63,  93,  97,  55],
       [ 88,  87,  89,  53,  82],
       [ 74,  57,  84,  71,  92],
       [ 82,  96,  69,  82,  95],
       [ 50,  99,  95,  90,  89],
       [ 92,  93,  89,  96,  98],
       [ 54,  76,  53,  87,  92],
       [ 69,  99,  70,  51,  97],
       [ 66,  96,  67,  55,  54],
       [ 50,  87,  86,  86,  82],
       [ 57,  70,  53,  57,  89],
       [ 76,  81,  64,  72,  98],
       [ 62,  52,  93,  67,  65],
       [ 61,  59,  85,  62,  51],
       [ 58,  86,  86,  81,  61],
       [ 58,  62,  94,  80,  94],
       [ 94,  